force-app/main/default/objects/Child_Object__c/Child_Object__c.object-meta.xml
<CustomObject>
    <label>Child Object</label>
    <nameField>
        <label>Child Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Childs_object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_Object__c/fields/Value_number__c.field-meta.xml
<CustomField>
    <fullName>Value_number__c</fullName>
    <label>Value number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parent_Object__c/Parent_Object__c.object-meta.xml
<CustomObject>
    <label>Parent Object</label>
    <nameField>
        <label>Parent Object Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent_Object__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Object</label>
    <referenceTo>Child_Object__c</referenceTo>
    <relationshipLabel>Parents Object</relationshipLabel>
    <relationshipName>Parents_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent_Object__c/fields/Date_and_time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_time__c</fullName>
    <label>Date and time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Parent_Object__c/fields/Sum_value_from_childs__c.field-meta.xml
<CustomField>
    <fullName>Sum_value_from_childs__c</fullName>
    <label>Sum value from childs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/test.cls
@isTest public class test {

    @isTest static void date_update_test(){
     List<Parent_Object__c> test_parent_object = new List<Parent_Object__c>();
        test_parent_object.add(new Parent_Object__c(Name = 'Parent test'));
        insert test_parent_object;
        update test_parent_object;
        List<Child_Object__c> test_child_object = new List<Child_Object__c>();
        test_child_object.add(new Child_Object__c(Name = 'Test 1', Value_number__c = 1));
        insert test_child_object;
        Datetime test_time;
        List<Parent_Object__c> test_parents_object = [SELECT Date_and_time__c FROM Parent_Object__c];
        for(Parent_Object__c parent_object : test_parents_object){
           test_time = (Datetime)parent_object.get('Date_and_time__c');
        }
        System.assertEquals(System.now(), test_time);
     }
    
    @isTest static void size_test(){
        List<Parent_Object__c> test_parent_object = new List<Parent_Object__c>();
        test_parent_object.add(new Parent_Object__c(Name = 'Parent test'));
        insert test_parent_object;
        update test_parent_object;       
    	List<Child_Object__c> test_child_object = new List<Child_Object__c>();
        test_child_object.add(new Child_Object__c(Name = 'Test 1',Value_number__c = 1));
        test_child_object.add(new Child_object__c(Name = 'Test 2',Value_number__c = 2));
        test_child_object.add(new Child_object__c(Name = 'Test 3',Value_number__c = 2));
        test_child_object.add(new Child_object__c(Name = 'Test 4',Value_number__c = 2));
        insert test_child_object;
        Decimal test_size;
        List<Parent_Object__c> test_parents_object = [SELECT Size__c FROM Parent_Object__c];
        for(Parent_Object__c parent_object : test_parents_object){
            test_size = (Decimal)parent_object.get('Size__c');
        } 
        System.assertEquals(test_child_object.size(), test_size);
    }  
    
    @isTest static void value_test(){
        List<Parent_Object__c> test_parent_object = new List<Parent_Object__c>();
        test_parent_object.add(new Parent_Object__c(Name = 'Parent test'));
        insert test_parent_object;
        update test_parent_object;  
        Decimal test_value_1 = 1;
        Decimal test_value_2 = 2;
        Decimal test_value_3 = 20;
        Decimal test_value_4 = 122;
    	List<Child_Object__c> test_child_object = new List<Child_Object__c>();
        test_child_object.add(new Child_Object__c(Name = 'Test 1', Value_number__c = test_value_1));
        test_child_object.add(new Child_object__c(Name = 'Test 2', Value_number__c = test_value_2));
		test_child_object.add(new Child_object__c(Name = 'Test 3', Value_number__c = test_value_3));
        test_child_object.add(new Child_object__c(Name = 'Test 4', Value_number__c = test_value_4));
        insert test_child_object;
        Decimal sum = 0;
        List<Parent_Object__c> test_parents_object = [SELECT Sum_value_from_childs__c FROM Parent_Object__c];
        for(Parent_Object__c parent_object : test_parents_object){
            sum += (Decimal) parent_object.get('Sum_value_from_childs__c');
        } 
        Double test_sum = test_value_1 + test_value_2 + test_value_3 + test_value_4;
        System.assertEquals(test_sum,sum);
    }  
}